
SELECT PLAN_ENRL_I,ENRL_PROV_GRP_I,ACCOUNT_NO,TAKEOVER_CARRIER_IND_C,PROV_GRP_SRCH_NM,PROV_GRP_DESC_T
FROM DBREGRC.PLAN_PROV_GRP
fetch first 1000 rows only;

SELECT PLAN_ENRL_I,ENRL_PROV_GRP_I,ACCOUNT_NO,TAKEOVER_CARRIER_IND_C,PROV_GRP_SRCH_NM,PROV_GRP_DESC_T
FROM DBREGRC.PLAN_PROV_GRP
WHERE ACCOUNT_NO like 'QK61311MB%' -- or ACCOUNT_NO like 'QK61311%'
;

SELECT PLAN_ENRL_I,ENRL_PROV_GRP_I,ACCOUNT_NO,TAKEOVER_CARRIER_IND_C,PROV_GRP_SRCH_NM,PROV_GRP_DESC_T
FROM DBREGRT.PLAN_PROV_GRP
WHERE ACCOUNT_NO like 'JK61963%' or ACCOUNT_NO like 'QK61311%'
;

SELECT PLAN_ENRL_I,ENRL_PROV_GRP_I,ACCOUNT_NO,TAKEOVER_CARRIER_IND_C,PROV_GRP_SRCH_NM,PROV_GRP_DESC_T
FROM DBREGRP.PLAN_PROV_GRP
WHERE ACCOUNT_NO like 'JK61963%' or ACCOUNT_NO like 'QK61311%'
;

--check if plan exists
SELECT *
FROM DBREGRC.CASE_DATA
WHERE CASE_NO like 'JK61963%' or CASE_NO like 'QK61311%'
;

SELECT *
FROM DBREGRT.CASE_DATA
WHERE CASE_NO like 'JK61963%' or CASE_NO like 'QK61311%'
;




SELECT  *
FROM    DBREGRC.EMPLOYEE
where CASE_NO like 'QK61543MB%'--'JK61963MB%' -- 'JK61963%' or CASE_NO like 'QK61311%'
order by mod_ts desc
for fetch only with ur
--fetch first 1000 rows only;
;

SELECT  *
FROM    DBREGRT.EMPLOYEE
where CASE_NO like 'JK61963MB%'--'JK61963%' or CASE_NO like 'QK61311%'
order by mod_ts desc
;

SELECT  *
FROM    DBREGRP.EMPLOYEE
where CASE_NO like 'JK61963%' or CASE_NO like 'QK61311%'
;

  

SELECT PLAN_ENRL_I
,ENRL_PROV_GRP_I
,ACCOUNT_NO
,TAKEOVER_CARRIER_IND_C
,PROV_GRP_SRCH_NM
,PROV_GRP_DESC_T
FROM DBREGRC.PLAN_PROV_GRP
WHERE 
--ACCOUNT_NO like 'A50878%'
TAKEOVER_CARRIER_IND_C = 1
;
--get these for testing: 651640QA  00001, 752912QA  00001, 752985QA  00001


SELECT  P.PLAN_ENRL_I, P.ENRL_PROV_GRP_I, P.ACCOUNT_NO, P.TAKEOVER_CARRIER_IND_C, P.PROV_GRP_SRCH_NM, P.PROV_GRP_DESC_T, E.SOC_SEC_NO, E.EE_FST_MID_NM, E.EE_LAST_NM,E.EE_HIRE_DT,E.EE_BRTH_DT
FROM    DBREGRC.PLAN_PROV_GRP P,
        DBREGRC.EMPLOYEE E
where  E.CASE_NO = P.ACCOUNT_NO 
--P.TAKEOVER_CARRIER_IND_C = 1
--and    P.ACCOUNT_NO = E.CASE_NO
order by E.MOD_TS desc
fetch first 1000 rows only;



-- Mercer plans with participant information on Employee
SELECT  P.PLAN_ENRL_I, P.ENRL_PROV_GRP_I, P.ACCOUNT_NO, P.TAKEOVER_CARRIER_IND_C, P.PROV_GRP_SRCH_NM, P.PROV_GRP_DESC_T, E.SOC_SEC_NO, E.EE_FST_MID_NM, E.EE_LAST_NM,E.EE_HIRE_DT,E.EE_BRTH_DT
FROM    DBREGRC.PLAN_PROV_GRP P,
        DBREGRC.EMPLOYEE E
where  P.ACCOUNT_NO = E.CASE_NO
and P.TAKEOVER_CARRIER_IND_C = 1
--and    P.ACCOUNT_NO = E.CASE_NO
order by E.MOD_TS desc
fetch first 1000 rows only;


SELECT  *
FROM    DBREGRC.EMPLOYEE
where CASE_NO in ('752333QA  00001', '751057CQA 00001')
order by MOD_TS desc
fetch first 1000 rows only;

SELECT  *
FROM    DBREGRC.EMPLOYEE
where case_no = '651640QA  00001'
--where ALT_PART_STAT_CD = '00'
order by MOD_TS desc
fetch first 1000 rows only;

SELECT  *
FROM    DBREGRC.EMPLOYEE
order by MOD_TS desc
fetch first 1000 rows only;


SELECT *
FROM DBREGRC.PLAN_PROV_GRP
WHERE 
--ACCOUNT_NO = 'A50878    00001'
TAKEOVER_CARRIER_IND_C = 1
;

SELECT PLAN_ENRL_I
,ENRL_PROV_GRP_I
,ACCOUNT_NO
,TAKEOVER_CARRIER_IND_C
,PROV_GRP_SRCH_NM
,PROV_GRP_DESC_T
FROM DBREGRC.PLAN_PROV_GRP
WHERE 
--ACCOUNT_NO = 'A50878    00001'
PROV_GRP_SRCH_NM like '%olvo%'
;